version: "3"

services:

  postgres:
    container_name: postgres
    image: "postgres:12.12-alpine"
    restart: "unless-stopped"
    networks:
      - db-network
    volumes:
      - db-volume:${POSTGRES_PGDATA}
    env_file:
      - .env

  backend:
    container_name: backend
    build: backend
    restart: "unless-stopped"
    networks:
      - db-network
      - http-network
    env_file:
      - .env
    ports:
      - "4000:3000"
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build: frontend
    restart: "unless-stopped"
    networks:
      - http-network
    ports:
      - "8081:80"

networks:
  db-network:
  http-network:

volumes:
  db-volume: